CREATE TABLE Dialogs
(
	id INT(11) PRIMARY KEY NOT NULL,
	dialogName VARCHAR(50) NOT NULL,
	dialogPicture VARCHAR(200) NOT NULL
);
CREATE TABLE Messages
(
	id INT(11) PRIMARY KEY NOT NULL,
	user INT(11) NOT NULL,
	createdDatetime DATETIME NOT NULL,
	dialog INT(11) NOT NULL,
	message VARCHAR(150) NOT NULL,
	CONSTRAINT Messages_fk0 FOREIGN KEY (user) REFERENCES Users (id),
	CONSTRAINT Messages_fk1 FOREIGN KEY (dialog) REFERENCES Dialogs (id)
);
CREATE INDEX Messages_fk0 ON Messages (user);
CREATE INDEX Messages_fk1 ON Messages (dialog);
CREATE TABLE Roles
(
	id INT(11) PRIMARY KEY NOT NULL,
	label VARCHAR(20) NOT NULL
);
CREATE UNIQUE INDEX label ON Roles (label);
CREATE TABLE Users
(
	id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	email VARCHAR(50) NOT NULL,
	firstName VARCHAR(20) NOT NULL,
	lastName VARCHAR(50) NOT NULL,
	role INT(11) NOT NULL,
	password VARCHAR(32) NOT NULL,
	CONSTRAINT Users_fk0 FOREIGN KEY (role) REFERENCES Roles (id)
);
CREATE UNIQUE INDEX email ON Users (email);
CREATE INDEX Users_fk0 ON Users (role);

